#
# Copyright (c) 2017-2025 Tencent. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set(bdrc_public_header
  include/tencentcloud/bdrc/v20260330/BdrcClient.h
  )

set(bdrc_public_header_model
  include/tencentcloud/bdrc/v20260330/model/DescribeCopyPairsDeniedActionsResponse.h
  include/tencentcloud/bdrc/v20260330/model/BackupDetail.h
  include/tencentcloud/bdrc/v20260330/model/DescribeFileBackupPlansRequest.h
  include/tencentcloud/bdrc/v20260330/model/ReportGatewayHeartbeatResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribeCopyPairsRequest.h
  include/tencentcloud/bdrc/v20260330/model/DescribeBackupVaultsDeniedActionsRequest.h
  include/tencentcloud/bdrc/v20260330/model/AdvancedRetentionPolicy.h
  include/tencentcloud/bdrc/v20260330/model/UnbindAutoBackupPolicyRequest.h
  include/tencentcloud/bdrc/v20260330/model/DescribeCopyPairsDeniedActionsRequest.h
  include/tencentcloud/bdrc/v20260330/model/ModifySitePairAttributeResponse.h
  include/tencentcloud/bdrc/v20260330/model/BasicServicesSettings.h
  include/tencentcloud/bdrc/v20260330/model/RunSecurityServiceEnabled.h
  include/tencentcloud/bdrc/v20260330/model/ModifyCopyPairAttributeRequest.h
  include/tencentcloud/bdrc/v20260330/model/BackupPlan.h
  include/tencentcloud/bdrc/v20260330/model/FilterModel.h
  include/tencentcloud/bdrc/v20260330/model/DiskModel.h
  include/tencentcloud/bdrc/v20260330/model/DeleteAutoBackupPoliciesResponse.h
  include/tencentcloud/bdrc/v20260330/model/RunCopyPairTasksRequest.h
  include/tencentcloud/bdrc/v20260330/model/DeleteFileBackupPlansRequest.h
  include/tencentcloud/bdrc/v20260330/model/CommonBackupPoint.h
  include/tencentcloud/bdrc/v20260330/model/DescribeBackupVaultsRequest.h
  include/tencentcloud/bdrc/v20260330/model/CreateAutoBackupPolicyRequest.h
  include/tencentcloud/bdrc/v20260330/model/ModifySitePairAttributeRequest.h
  include/tencentcloud/bdrc/v20260330/model/RunCopyPairTasksResponse.h
  include/tencentcloud/bdrc/v20260330/model/CrossCloudDetails.h
  include/tencentcloud/bdrc/v20260330/model/CreateDisasterRecoveryVpcMappingResponse.h
  include/tencentcloud/bdrc/v20260330/model/DisasterRecoveryDrillGroup.h
  include/tencentcloud/bdrc/v20260330/model/VaultDeniedAction.h
  include/tencentcloud/bdrc/v20260330/model/ReportJobProgressRequest.h
  include/tencentcloud/bdrc/v20260330/model/BackupDeniedAction.h
  include/tencentcloud/bdrc/v20260330/model/ModifyDrillGroupAttributeRequest.h
  include/tencentcloud/bdrc/v20260330/model/ModifyFileBackupAttributeRequest.h
  include/tencentcloud/bdrc/v20260330/model/DeleteDisasterRecoverySitePairsResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribeDisasterRecoverySitePairsDeniedActionsResponse.h
  include/tencentcloud/bdrc/v20260330/model/ProtectInstance.h
  include/tencentcloud/bdrc/v20260330/model/DeleteDrillPairsRequest.h
  include/tencentcloud/bdrc/v20260330/model/DescribeFileRestoreTasksRequest.h
  include/tencentcloud/bdrc/v20260330/model/DescribeBackupPlansRequest.h
  include/tencentcloud/bdrc/v20260330/model/DeleteDrillPairResult.h
  include/tencentcloud/bdrc/v20260330/model/DescribeBackupGroupsRequest.h
  include/tencentcloud/bdrc/v20260330/model/DescribeBackupGroupRollbackTasksRequest.h
  include/tencentcloud/bdrc/v20260330/model/ModifyAutoBackupPolicyAttributeResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribeFileBackupsDeniedActionsRequest.h
  include/tencentcloud/bdrc/v20260330/model/ModifyFileBackupPlanRequest.h
  include/tencentcloud/bdrc/v20260330/model/RunInstancesWithBackupGroupRequest.h
  include/tencentcloud/bdrc/v20260330/model/DeleteDisasterRecoveryProtectGroupsRequest.h
  include/tencentcloud/bdrc/v20260330/model/ProtectedResourceStatus.h
  include/tencentcloud/bdrc/v20260330/model/CreateBackupGroupRequest.h
  include/tencentcloud/bdrc/v20260330/model/CreateSecurityGroupMappingRequest.h
  include/tencentcloud/bdrc/v20260330/model/ResourceProtectStat.h
  include/tencentcloud/bdrc/v20260330/model/ModifyCopyPairAttributeResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribeBackupGroupsDeniedActionsResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribeVpcMappingsResponse.h
  include/tencentcloud/bdrc/v20260330/model/ProtectGroup.h
  include/tencentcloud/bdrc/v20260330/model/RunInstancesWithBackupGroupResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribeAutoBackupPoliciesRequest.h
  include/tencentcloud/bdrc/v20260330/model/Placement.h
  include/tencentcloud/bdrc/v20260330/model/DeleteBackupGroupsResponse.h
  include/tencentcloud/bdrc/v20260330/model/BackupInfo.h
  include/tencentcloud/bdrc/v20260330/model/DescribeBackupPlansResponse.h
  include/tencentcloud/bdrc/v20260330/model/Policy.h
  include/tencentcloud/bdrc/v20260330/model/ModifyBackupVaultAttributeResponse.h
  include/tencentcloud/bdrc/v20260330/model/DrillPairDeniedAction.h
  include/tencentcloud/bdrc/v20260330/model/CreateFileBackupResponse.h
  include/tencentcloud/bdrc/v20260330/model/ApplyBackupGroupResponse.h
  include/tencentcloud/bdrc/v20260330/model/BackupInstance.h
  include/tencentcloud/bdrc/v20260330/model/DescribeFileBackupsRequest.h
  include/tencentcloud/bdrc/v20260330/model/DescribeBackupInstancesResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribeCopyPairsResponse.h
  include/tencentcloud/bdrc/v20260330/model/DeleteSecurityGroupMappingResponse.h
  include/tencentcloud/bdrc/v20260330/model/CreateDisasterRecoverySitePairResponse.h
  include/tencentcloud/bdrc/v20260330/model/DeleteBackupVaultsResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribeCommonBackupPointsRequest.h
  include/tencentcloud/bdrc/v20260330/model/DescribeFileBackupObjectsRequest.h
  include/tencentcloud/bdrc/v20260330/model/CreateDisasterRecoverySitePairRequest.h
  include/tencentcloud/bdrc/v20260330/model/DescribeDisksResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribePriceCreateCopyPairsRequest.h
  include/tencentcloud/bdrc/v20260330/model/CreateDisasterRecoveryProtectGroupRequest.h
  include/tencentcloud/bdrc/v20260330/model/CreateInstanceCopyPairRequest.h
  include/tencentcloud/bdrc/v20260330/model/ReportGatewayHeartbeatRequest.h
  include/tencentcloud/bdrc/v20260330/model/DeleteDisasterRecoverySitePairsRequest.h
  include/tencentcloud/bdrc/v20260330/model/ProtectedResource.h
  include/tencentcloud/bdrc/v20260330/model/CopyPairDeniedAction.h
  include/tencentcloud/bdrc/v20260330/model/CreateFileBackupRequest.h
  include/tencentcloud/bdrc/v20260330/model/DescribeFileBackupObjectsResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribeFileRestoreTasksResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribeFileBackupPlansResponse.h
  include/tencentcloud/bdrc/v20260330/model/BackupGroup.h
  include/tencentcloud/bdrc/v20260330/model/ModifyDrillPairAttributeResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribeBackupVaultsResponse.h
  include/tencentcloud/bdrc/v20260330/model/ModifyBackupVaultAttributeRequest.h
  include/tencentcloud/bdrc/v20260330/model/DescribeDrillPairsDeniedActionsRequest.h
  include/tencentcloud/bdrc/v20260330/model/CopyPair.h
  include/tencentcloud/bdrc/v20260330/model/DescribeDisasterRecoverySupportRegionResponse.h
  include/tencentcloud/bdrc/v20260330/model/DrilledResourceStatus.h
  include/tencentcloud/bdrc/v20260330/model/ReportJobProgressResponse.h
  include/tencentcloud/bdrc/v20260330/model/FileBackupOverview.h
  include/tencentcloud/bdrc/v20260330/model/PlanInfo.h
  include/tencentcloud/bdrc/v20260330/model/DeleteFileBackupsResponse.h
  include/tencentcloud/bdrc/v20260330/model/BindAutoBackupPolicyRequest.h
  include/tencentcloud/bdrc/v20260330/model/DescribeDisasterRecoverySitePairsResponse.h
  include/tencentcloud/bdrc/v20260330/model/CreateFileBackupPlanResponse.h
  include/tencentcloud/bdrc/v20260330/model/CreateFileBackupPlanRequest.h
  include/tencentcloud/bdrc/v20260330/model/ReportAgentMetricsResponse.h
  include/tencentcloud/bdrc/v20260330/model/ModifyFileBackupAttributeResponse.h
  include/tencentcloud/bdrc/v20260330/model/LoginSettings.h
  include/tencentcloud/bdrc/v20260330/model/BackupGroupDeniedAction.h
  include/tencentcloud/bdrc/v20260330/model/CreateDisasterRecoveryProtectGroupResponse.h
  include/tencentcloud/bdrc/v20260330/model/EnhancedService.h
  include/tencentcloud/bdrc/v20260330/model/ProtectedResourceOverview.h
  include/tencentcloud/bdrc/v20260330/model/BackupGroupRollbackTask.h
  include/tencentcloud/bdrc/v20260330/model/CreateBackupGroupResponse.h
  include/tencentcloud/bdrc/v20260330/model/SupportZoneRule.h
  include/tencentcloud/bdrc/v20260330/model/DescribeDisasterRecoveryOverviewResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribeAutoBackupPoliciesResponse.h
  include/tencentcloud/bdrc/v20260330/model/CreateFileRestoreTaskRequest.h
  include/tencentcloud/bdrc/v20260330/model/AspInfo.h
  include/tencentcloud/bdrc/v20260330/model/TypeCount.h
  include/tencentcloud/bdrc/v20260330/model/DescribeFileBackupsDeniedActionsResponse.h
  include/tencentcloud/bdrc/v20260330/model/DeniedAction.h
  include/tencentcloud/bdrc/v20260330/model/DescribeDisasterRecoveryProtectGroupsRequest.h
  include/tencentcloud/bdrc/v20260330/model/BackupVault.h
  include/tencentcloud/bdrc/v20260330/model/UnbindAutoBackupPolicyResponse.h
  include/tencentcloud/bdrc/v20260330/model/StopCopyPairTasksResponse.h
  include/tencentcloud/bdrc/v20260330/model/ResourcePlan.h
  include/tencentcloud/bdrc/v20260330/model/CreateInstanceDrillPairsResponse.h
  include/tencentcloud/bdrc/v20260330/model/DeleteBackupGroupsRequest.h
  include/tencentcloud/bdrc/v20260330/model/CreateInstanceCopyPairResponse.h
  include/tencentcloud/bdrc/v20260330/model/DiskInfo.h
  include/tencentcloud/bdrc/v20260330/model/FinishFailoverCopyPairsRequest.h
  include/tencentcloud/bdrc/v20260330/model/DescribeDisasterRecoverySupportRegionRequest.h
  include/tencentcloud/bdrc/v20260330/model/CreateDisasterRecoveryVpcMappingRequest.h
  include/tencentcloud/bdrc/v20260330/model/DescribeBackupVaultsDeniedActionsResponse.h
  include/tencentcloud/bdrc/v20260330/model/AutoBackupPolicy.h
  include/tencentcloud/bdrc/v20260330/model/RestoreTask.h
  include/tencentcloud/bdrc/v20260330/model/CreateFileRestoreTaskResponse.h
  include/tencentcloud/bdrc/v20260330/model/ModifyDrillPairAttributeRequest.h
  include/tencentcloud/bdrc/v20260330/model/CreateAutoBackupPolicyResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribeDisasterRecoveryProtectGroupsResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribeSecurityGroupMappingsRequest.h
  include/tencentcloud/bdrc/v20260330/model/CreateBackupVaultRequest.h
  include/tencentcloud/bdrc/v20260330/model/DeleteCopyPairsRequest.h
  include/tencentcloud/bdrc/v20260330/model/DeleteSecurityGroupMappingRequest.h
  include/tencentcloud/bdrc/v20260330/model/CreateInstanceModel.h
  include/tencentcloud/bdrc/v20260330/model/DrillPair.h
  include/tencentcloud/bdrc/v20260330/model/DescribeDisasterRecoveryOverviewRequest.h
  include/tencentcloud/bdrc/v20260330/model/ModifyAutoBackupPolicyAttributeRequest.h
  include/tencentcloud/bdrc/v20260330/model/DeleteCopyPairsResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribeDisasterRecoverySitePairsRequest.h
  include/tencentcloud/bdrc/v20260330/model/DeleteBackupVaultsRequest.h
  include/tencentcloud/bdrc/v20260330/model/DeleteDisasterRecoveryVpcMappingRequest.h
  include/tencentcloud/bdrc/v20260330/model/ProtectGroupDeniedAction.h
  include/tencentcloud/bdrc/v20260330/model/DescribeDisksRequest.h
  include/tencentcloud/bdrc/v20260330/model/CreateInstanceDrillPairsRequest.h
  include/tencentcloud/bdrc/v20260330/model/DeleteFileBackupPlansResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribeBackupGroupsDeniedActionsRequest.h
  include/tencentcloud/bdrc/v20260330/model/FinishFailoverCopyPairsResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribeJobsRequest.h
  include/tencentcloud/bdrc/v20260330/model/ModifyFileBackupPlanResponse.h
  include/tencentcloud/bdrc/v20260330/model/ModifyBackupAttributeRequest.h
  include/tencentcloud/bdrc/v20260330/model/DescribeBackupInstancesRequest.h
  include/tencentcloud/bdrc/v20260330/model/DeleteDisasterRecoveryProtectGroupsResponse.h
  include/tencentcloud/bdrc/v20260330/model/ModifyBackupAttributeResponse.h
  include/tencentcloud/bdrc/v20260330/model/ModifyProtectGroupAttributeRequest.h
  include/tencentcloud/bdrc/v20260330/model/DescribeProtectedInstancesResponse.h
  include/tencentcloud/bdrc/v20260330/model/CreateBackupVaultResponse.h
  include/tencentcloud/bdrc/v20260330/model/InstanceBackupOverview.h
  include/tencentcloud/bdrc/v20260330/model/DescribeDrillPairsDeniedActionsResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribeProtectGroupsDeniedActionsRequest.h
  include/tencentcloud/bdrc/v20260330/model/SitePairDeniedAction.h
  include/tencentcloud/bdrc/v20260330/model/CreateSecurityGroupMappingResponse.h
  include/tencentcloud/bdrc/v20260330/model/ApplyBackupGroupRequest.h
  include/tencentcloud/bdrc/v20260330/model/DeleteDisasterRecoveryVpcMappingResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribeProtectGroupsDeniedActionsResponse.h
  include/tencentcloud/bdrc/v20260330/model/StopCopyPairTasksRequest.h
  include/tencentcloud/bdrc/v20260330/model/CopyPairPriceDetail.h
  include/tencentcloud/bdrc/v20260330/model/DeleteFileBackupsRequest.h
  include/tencentcloud/bdrc/v20260330/model/DiskCopyPairForCvm.h
  include/tencentcloud/bdrc/v20260330/model/DescribeDrillPairsResponse.h
  include/tencentcloud/bdrc/v20260330/model/ModifyDrillGroupAttributeResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribeDrillPairsRequest.h
  include/tencentcloud/bdrc/v20260330/model/DeleteAutoBackupPoliciesRequest.h
  include/tencentcloud/bdrc/v20260330/model/SecurityGroupMapping.h
  include/tencentcloud/bdrc/v20260330/model/RunFailoverCopyPairsResponse.h
  include/tencentcloud/bdrc/v20260330/model/ModifyProtectGroupAttributeResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribeDisasterRecoveryDrillGroupsRequest.h
  include/tencentcloud/bdrc/v20260330/model/DescribeBackupGroupsResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribeDisasterRecoveryDrillGroupsResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribeBackupOverviewGeneralRequest.h
  include/tencentcloud/bdrc/v20260330/model/BindAutoBackupPolicyResponse.h
  include/tencentcloud/bdrc/v20260330/model/FlowControlRule.h
  include/tencentcloud/bdrc/v20260330/model/SitePair.h
  include/tencentcloud/bdrc/v20260330/model/SupportRegionInfo.h
  include/tencentcloud/bdrc/v20260330/model/RunFailoverCopyPairsRequest.h
  include/tencentcloud/bdrc/v20260330/model/DescribeFileBackupsResponse.h
  include/tencentcloud/bdrc/v20260330/model/AutomationServiceEnabled.h
  include/tencentcloud/bdrc/v20260330/model/DescribeJobsResponse.h
  include/tencentcloud/bdrc/v20260330/model/BackupPolicyOverview.h
  include/tencentcloud/bdrc/v20260330/model/DisasterRecoveryOverview.h
  include/tencentcloud/bdrc/v20260330/model/DescribeBackupGroupRollbackTasksResponse.h
  include/tencentcloud/bdrc/v20260330/model/VirtualPrivateCloud.h
  include/tencentcloud/bdrc/v20260330/model/DescribeSecurityGroupMappingsResponse.h
  include/tencentcloud/bdrc/v20260330/model/DeleteDrillPairsResponse.h
  include/tencentcloud/bdrc/v20260330/model/DescribeVpcMappingsRequest.h
  include/tencentcloud/bdrc/v20260330/model/CopyPairPrice.h
  include/tencentcloud/bdrc/v20260330/model/BackupVaultOverview.h
  include/tencentcloud/bdrc/v20260330/model/DescribeBackupOverviewGeneralResponse.h
  include/tencentcloud/bdrc/v20260330/model/ApplyDisk.h
  include/tencentcloud/bdrc/v20260330/model/VpcMapping.h
  include/tencentcloud/bdrc/v20260330/model/ReportAgentMetricsRequest.h
  include/tencentcloud/bdrc/v20260330/model/InternetAccessible.h
  include/tencentcloud/bdrc/v20260330/model/DescribeProtectedInstancesRequest.h
  include/tencentcloud/bdrc/v20260330/model/DescribeDisasterRecoverySitePairsDeniedActionsRequest.h
  include/tencentcloud/bdrc/v20260330/model/DescribeCommonBackupPointsResponse.h
  include/tencentcloud/bdrc/v20260330/model/InstanceChargePrepaid.h
  include/tencentcloud/bdrc/v20260330/model/DescribePriceCreateCopyPairsResponse.h
  )

set(bdrc_src
  src/v20260330/BdrcClient.cpp
  src/v20260330/model/DescribeCopyPairsDeniedActionsResponse.cpp
  src/v20260330/model/BackupDetail.cpp
  src/v20260330/model/DescribeFileBackupPlansRequest.cpp
  src/v20260330/model/ReportGatewayHeartbeatResponse.cpp
  src/v20260330/model/DescribeCopyPairsRequest.cpp
  src/v20260330/model/DescribeBackupVaultsDeniedActionsRequest.cpp
  src/v20260330/model/AdvancedRetentionPolicy.cpp
  src/v20260330/model/UnbindAutoBackupPolicyRequest.cpp
  src/v20260330/model/DescribeCopyPairsDeniedActionsRequest.cpp
  src/v20260330/model/ModifySitePairAttributeResponse.cpp
  src/v20260330/model/BasicServicesSettings.cpp
  src/v20260330/model/RunSecurityServiceEnabled.cpp
  src/v20260330/model/ModifyCopyPairAttributeRequest.cpp
  src/v20260330/model/BackupPlan.cpp
  src/v20260330/model/FilterModel.cpp
  src/v20260330/model/DiskModel.cpp
  src/v20260330/model/DeleteAutoBackupPoliciesResponse.cpp
  src/v20260330/model/RunCopyPairTasksRequest.cpp
  src/v20260330/model/DeleteFileBackupPlansRequest.cpp
  src/v20260330/model/CommonBackupPoint.cpp
  src/v20260330/model/DescribeBackupVaultsRequest.cpp
  src/v20260330/model/CreateAutoBackupPolicyRequest.cpp
  src/v20260330/model/ModifySitePairAttributeRequest.cpp
  src/v20260330/model/RunCopyPairTasksResponse.cpp
  src/v20260330/model/CrossCloudDetails.cpp
  src/v20260330/model/CreateDisasterRecoveryVpcMappingResponse.cpp
  src/v20260330/model/DisasterRecoveryDrillGroup.cpp
  src/v20260330/model/VaultDeniedAction.cpp
  src/v20260330/model/ReportJobProgressRequest.cpp
  src/v20260330/model/BackupDeniedAction.cpp
  src/v20260330/model/ModifyDrillGroupAttributeRequest.cpp
  src/v20260330/model/ModifyFileBackupAttributeRequest.cpp
  src/v20260330/model/DeleteDisasterRecoverySitePairsResponse.cpp
  src/v20260330/model/DescribeDisasterRecoverySitePairsDeniedActionsResponse.cpp
  src/v20260330/model/ProtectInstance.cpp
  src/v20260330/model/DeleteDrillPairsRequest.cpp
  src/v20260330/model/DescribeFileRestoreTasksRequest.cpp
  src/v20260330/model/DescribeBackupPlansRequest.cpp
  src/v20260330/model/DeleteDrillPairResult.cpp
  src/v20260330/model/DescribeBackupGroupsRequest.cpp
  src/v20260330/model/DescribeBackupGroupRollbackTasksRequest.cpp
  src/v20260330/model/ModifyAutoBackupPolicyAttributeResponse.cpp
  src/v20260330/model/DescribeFileBackupsDeniedActionsRequest.cpp
  src/v20260330/model/ModifyFileBackupPlanRequest.cpp
  src/v20260330/model/RunInstancesWithBackupGroupRequest.cpp
  src/v20260330/model/DeleteDisasterRecoveryProtectGroupsRequest.cpp
  src/v20260330/model/ProtectedResourceStatus.cpp
  src/v20260330/model/CreateBackupGroupRequest.cpp
  src/v20260330/model/CreateSecurityGroupMappingRequest.cpp
  src/v20260330/model/ResourceProtectStat.cpp
  src/v20260330/model/ModifyCopyPairAttributeResponse.cpp
  src/v20260330/model/DescribeBackupGroupsDeniedActionsResponse.cpp
  src/v20260330/model/DescribeVpcMappingsResponse.cpp
  src/v20260330/model/ProtectGroup.cpp
  src/v20260330/model/RunInstancesWithBackupGroupResponse.cpp
  src/v20260330/model/DescribeAutoBackupPoliciesRequest.cpp
  src/v20260330/model/Placement.cpp
  src/v20260330/model/DeleteBackupGroupsResponse.cpp
  src/v20260330/model/BackupInfo.cpp
  src/v20260330/model/DescribeBackupPlansResponse.cpp
  src/v20260330/model/Policy.cpp
  src/v20260330/model/ModifyBackupVaultAttributeResponse.cpp
  src/v20260330/model/DrillPairDeniedAction.cpp
  src/v20260330/model/CreateFileBackupResponse.cpp
  src/v20260330/model/ApplyBackupGroupResponse.cpp
  src/v20260330/model/BackupInstance.cpp
  src/v20260330/model/DescribeFileBackupsRequest.cpp
  src/v20260330/model/DescribeBackupInstancesResponse.cpp
  src/v20260330/model/DescribeCopyPairsResponse.cpp
  src/v20260330/model/DeleteSecurityGroupMappingResponse.cpp
  src/v20260330/model/CreateDisasterRecoverySitePairResponse.cpp
  src/v20260330/model/DeleteBackupVaultsResponse.cpp
  src/v20260330/model/DescribeCommonBackupPointsRequest.cpp
  src/v20260330/model/DescribeFileBackupObjectsRequest.cpp
  src/v20260330/model/CreateDisasterRecoverySitePairRequest.cpp
  src/v20260330/model/DescribeDisksResponse.cpp
  src/v20260330/model/DescribePriceCreateCopyPairsRequest.cpp
  src/v20260330/model/CreateDisasterRecoveryProtectGroupRequest.cpp
  src/v20260330/model/CreateInstanceCopyPairRequest.cpp
  src/v20260330/model/ReportGatewayHeartbeatRequest.cpp
  src/v20260330/model/DeleteDisasterRecoverySitePairsRequest.cpp
  src/v20260330/model/ProtectedResource.cpp
  src/v20260330/model/CopyPairDeniedAction.cpp
  src/v20260330/model/CreateFileBackupRequest.cpp
  src/v20260330/model/DescribeFileBackupObjectsResponse.cpp
  src/v20260330/model/DescribeFileRestoreTasksResponse.cpp
  src/v20260330/model/DescribeFileBackupPlansResponse.cpp
  src/v20260330/model/BackupGroup.cpp
  src/v20260330/model/ModifyDrillPairAttributeResponse.cpp
  src/v20260330/model/DescribeBackupVaultsResponse.cpp
  src/v20260330/model/ModifyBackupVaultAttributeRequest.cpp
  src/v20260330/model/DescribeDrillPairsDeniedActionsRequest.cpp
  src/v20260330/model/CopyPair.cpp
  src/v20260330/model/DescribeDisasterRecoverySupportRegionResponse.cpp
  src/v20260330/model/DrilledResourceStatus.cpp
  src/v20260330/model/ReportJobProgressResponse.cpp
  src/v20260330/model/FileBackupOverview.cpp
  src/v20260330/model/PlanInfo.cpp
  src/v20260330/model/DeleteFileBackupsResponse.cpp
  src/v20260330/model/BindAutoBackupPolicyRequest.cpp
  src/v20260330/model/DescribeDisasterRecoverySitePairsResponse.cpp
  src/v20260330/model/CreateFileBackupPlanResponse.cpp
  src/v20260330/model/CreateFileBackupPlanRequest.cpp
  src/v20260330/model/ReportAgentMetricsResponse.cpp
  src/v20260330/model/ModifyFileBackupAttributeResponse.cpp
  src/v20260330/model/LoginSettings.cpp
  src/v20260330/model/BackupGroupDeniedAction.cpp
  src/v20260330/model/CreateDisasterRecoveryProtectGroupResponse.cpp
  src/v20260330/model/EnhancedService.cpp
  src/v20260330/model/ProtectedResourceOverview.cpp
  src/v20260330/model/BackupGroupRollbackTask.cpp
  src/v20260330/model/CreateBackupGroupResponse.cpp
  src/v20260330/model/SupportZoneRule.cpp
  src/v20260330/model/DescribeDisasterRecoveryOverviewResponse.cpp
  src/v20260330/model/DescribeAutoBackupPoliciesResponse.cpp
  src/v20260330/model/CreateFileRestoreTaskRequest.cpp
  src/v20260330/model/AspInfo.cpp
  src/v20260330/model/TypeCount.cpp
  src/v20260330/model/DescribeFileBackupsDeniedActionsResponse.cpp
  src/v20260330/model/DeniedAction.cpp
  src/v20260330/model/DescribeDisasterRecoveryProtectGroupsRequest.cpp
  src/v20260330/model/BackupVault.cpp
  src/v20260330/model/UnbindAutoBackupPolicyResponse.cpp
  src/v20260330/model/StopCopyPairTasksResponse.cpp
  src/v20260330/model/ResourcePlan.cpp
  src/v20260330/model/CreateInstanceDrillPairsResponse.cpp
  src/v20260330/model/DeleteBackupGroupsRequest.cpp
  src/v20260330/model/CreateInstanceCopyPairResponse.cpp
  src/v20260330/model/DiskInfo.cpp
  src/v20260330/model/FinishFailoverCopyPairsRequest.cpp
  src/v20260330/model/DescribeDisasterRecoverySupportRegionRequest.cpp
  src/v20260330/model/CreateDisasterRecoveryVpcMappingRequest.cpp
  src/v20260330/model/DescribeBackupVaultsDeniedActionsResponse.cpp
  src/v20260330/model/AutoBackupPolicy.cpp
  src/v20260330/model/RestoreTask.cpp
  src/v20260330/model/CreateFileRestoreTaskResponse.cpp
  src/v20260330/model/ModifyDrillPairAttributeRequest.cpp
  src/v20260330/model/CreateAutoBackupPolicyResponse.cpp
  src/v20260330/model/DescribeDisasterRecoveryProtectGroupsResponse.cpp
  src/v20260330/model/DescribeSecurityGroupMappingsRequest.cpp
  src/v20260330/model/CreateBackupVaultRequest.cpp
  src/v20260330/model/DeleteCopyPairsRequest.cpp
  src/v20260330/model/DeleteSecurityGroupMappingRequest.cpp
  src/v20260330/model/CreateInstanceModel.cpp
  src/v20260330/model/DrillPair.cpp
  src/v20260330/model/DescribeDisasterRecoveryOverviewRequest.cpp
  src/v20260330/model/ModifyAutoBackupPolicyAttributeRequest.cpp
  src/v20260330/model/DeleteCopyPairsResponse.cpp
  src/v20260330/model/DescribeDisasterRecoverySitePairsRequest.cpp
  src/v20260330/model/DeleteBackupVaultsRequest.cpp
  src/v20260330/model/DeleteDisasterRecoveryVpcMappingRequest.cpp
  src/v20260330/model/ProtectGroupDeniedAction.cpp
  src/v20260330/model/DescribeDisksRequest.cpp
  src/v20260330/model/CreateInstanceDrillPairsRequest.cpp
  src/v20260330/model/DeleteFileBackupPlansResponse.cpp
  src/v20260330/model/DescribeBackupGroupsDeniedActionsRequest.cpp
  src/v20260330/model/FinishFailoverCopyPairsResponse.cpp
  src/v20260330/model/DescribeJobsRequest.cpp
  src/v20260330/model/ModifyFileBackupPlanResponse.cpp
  src/v20260330/model/ModifyBackupAttributeRequest.cpp
  src/v20260330/model/DescribeBackupInstancesRequest.cpp
  src/v20260330/model/DeleteDisasterRecoveryProtectGroupsResponse.cpp
  src/v20260330/model/ModifyBackupAttributeResponse.cpp
  src/v20260330/model/ModifyProtectGroupAttributeRequest.cpp
  src/v20260330/model/DescribeProtectedInstancesResponse.cpp
  src/v20260330/model/CreateBackupVaultResponse.cpp
  src/v20260330/model/InstanceBackupOverview.cpp
  src/v20260330/model/DescribeDrillPairsDeniedActionsResponse.cpp
  src/v20260330/model/DescribeProtectGroupsDeniedActionsRequest.cpp
  src/v20260330/model/SitePairDeniedAction.cpp
  src/v20260330/model/CreateSecurityGroupMappingResponse.cpp
  src/v20260330/model/ApplyBackupGroupRequest.cpp
  src/v20260330/model/DeleteDisasterRecoveryVpcMappingResponse.cpp
  src/v20260330/model/DescribeProtectGroupsDeniedActionsResponse.cpp
  src/v20260330/model/StopCopyPairTasksRequest.cpp
  src/v20260330/model/CopyPairPriceDetail.cpp
  src/v20260330/model/DeleteFileBackupsRequest.cpp
  src/v20260330/model/DiskCopyPairForCvm.cpp
  src/v20260330/model/DescribeDrillPairsResponse.cpp
  src/v20260330/model/ModifyDrillGroupAttributeResponse.cpp
  src/v20260330/model/DescribeDrillPairsRequest.cpp
  src/v20260330/model/DeleteAutoBackupPoliciesRequest.cpp
  src/v20260330/model/SecurityGroupMapping.cpp
  src/v20260330/model/RunFailoverCopyPairsResponse.cpp
  src/v20260330/model/ModifyProtectGroupAttributeResponse.cpp
  src/v20260330/model/DescribeDisasterRecoveryDrillGroupsRequest.cpp
  src/v20260330/model/DescribeBackupGroupsResponse.cpp
  src/v20260330/model/DescribeDisasterRecoveryDrillGroupsResponse.cpp
  src/v20260330/model/DescribeBackupOverviewGeneralRequest.cpp
  src/v20260330/model/BindAutoBackupPolicyResponse.cpp
  src/v20260330/model/FlowControlRule.cpp
  src/v20260330/model/SitePair.cpp
  src/v20260330/model/SupportRegionInfo.cpp
  src/v20260330/model/RunFailoverCopyPairsRequest.cpp
  src/v20260330/model/DescribeFileBackupsResponse.cpp
  src/v20260330/model/AutomationServiceEnabled.cpp
  src/v20260330/model/DescribeJobsResponse.cpp
  src/v20260330/model/BackupPolicyOverview.cpp
  src/v20260330/model/DisasterRecoveryOverview.cpp
  src/v20260330/model/DescribeBackupGroupRollbackTasksResponse.cpp
  src/v20260330/model/VirtualPrivateCloud.cpp
  src/v20260330/model/DescribeSecurityGroupMappingsResponse.cpp
  src/v20260330/model/DeleteDrillPairsResponse.cpp
  src/v20260330/model/DescribeVpcMappingsRequest.cpp
  src/v20260330/model/CopyPairPrice.cpp
  src/v20260330/model/BackupVaultOverview.cpp
  src/v20260330/model/DescribeBackupOverviewGeneralResponse.cpp
  src/v20260330/model/ApplyDisk.cpp
  src/v20260330/model/VpcMapping.cpp
  src/v20260330/model/ReportAgentMetricsRequest.cpp
  src/v20260330/model/InternetAccessible.cpp
  src/v20260330/model/DescribeProtectedInstancesRequest.cpp
  src/v20260330/model/DescribeDisasterRecoverySitePairsDeniedActionsRequest.cpp
  src/v20260330/model/DescribeCommonBackupPointsResponse.cpp
  src/v20260330/model/InstanceChargePrepaid.cpp
  src/v20260330/model/DescribePriceCreateCopyPairsResponse.cpp
  )

set(bdrc_include
    include/tencentcloud/bdrc
  )

add_library(bdrc ${LIB_TYPE}
  ${bdrc_public_header}
  ${bdrc_public_header_model}
  ${bdrc_src})

set_target_properties(bdrc
  PROPERTIES
  LINKER_LANGUAGE CXX
  ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib
  LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib
  RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin
  OUTPUT_NAME ${TARGET_OUTPUT_NAME_PREFIX}bdrc
  )

target_include_directories(bdrc
  PRIVATE include
    ${CMAKE_SOURCE_DIR}/core/include
  )
target_link_libraries(bdrc
  core)

#install(FILES ${bdrc_public_header}
#  DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/tencentcloud/bdrc/v20260330)
#install(FILES ${bdrc_public_header_model}
#  DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/tencentcloud/bdrc/v20260330/model)
install(DIRECTORY ${bdrc_include}
  DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/tencentcloud)

install(TARGETS bdrc
  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
  RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
  )
